apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delaparra-cloud
resources:
# Postgres
  - postgres/secret.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - postgres/pvc.yaml
# Nextcloud
  - nextcloud/deployment.yaml
  - nextcloud/service.yaml
  - nextcloud/ingress.yaml
  - nextcloud/pvc.yaml
